# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MPMS_gui_v0_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setObjectName("MainWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.MainWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainFrame = QtWidgets.QFrame(self.MainWidget)
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FileFrame = QtWidgets.QFrame(self.MainFrame)
        self.FileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FileFrame.setObjectName("FileFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.FileFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.FileFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.FileFrame)
        self.DisplayFrame = QtWidgets.QFrame(self.MainFrame)
        self.DisplayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DisplayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DisplayFrame.setObjectName("DisplayFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.DisplayFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PlotFrame = QtWidgets.QFrame(self.DisplayFrame)
        self.PlotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PlotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PlotFrame.setObjectName("PlotFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PlotFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PlotWidget = MplWidget(self.PlotFrame)
        self.PlotWidget.setObjectName("PlotWidget")
        self.gridLayout_2.addWidget(self.PlotWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.PlotFrame)
        self.PropertiesFrame = QtWidgets.QFrame(self.DisplayFrame)
        self.PropertiesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PropertiesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PropertiesFrame.setObjectName("PropertiesFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.PropertiesFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(335, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.PropertiesFrame)
        self.horizontalLayout.addWidget(self.DisplayFrame)
        self.gridLayout.addWidget(self.MainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.MainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "x"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "y"))
from display.mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
